"""Add type column to sub_task

Revision ID: 469fbdcb2cd8
Revises: 08e30c75e1ab
Create Date: 2025-07-19 13:12:48.758166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '469fbdcb2cd8'
down_revision = '08e30c75e1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprint')
    with op.batch_alter_table('sub_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('bug', 'update', 'feature', 'test', name='subtasktype'), nullable=False))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_sprint_id_fkey'), type_='foreignkey')
        batch_op.drop_column('sprint_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('task_sprint_id_fkey'), 'sprint', ['sprint_id'], ['id'])

    with op.batch_alter_table('sub_task', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.create_table('sprint',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('sprint_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sprint_pkey'))
    )
    # ### end Alembic commands ###
