"""Initial migration

Revision ID: 6a7bf37497e9
Revises: 
Create Date: 2025-07-13 11:23:53.427417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7bf37497e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('task_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='CASCADE')

    

    with op.batch_alter_table('team_project', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('team_project_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('team_project_project_id_fkey'), 'project', ['project_id'], ['id'])

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('task_project_id_fkey'), 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###
