"""Add summary and priority to Task table

Revision ID: 790f0931965f
Revises: d346d35c6df1
Create Date: 2025-07-11 10:24:15.096282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790f0931965f'
down_revision = 'd346d35c6df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='prioritylevel'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
