"""add_status_to_sprint

Revision ID: 8fcbc0f6c6e6
Revises: 3449feee9e60
Create Date: 2025-12-21 00:41:59.783468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcbc0f6c6e6'
down_revision = '3449feee9e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    sprintstatus = sa.Enum('planning', 'active', 'completed', 'archived', name='sprintstatus')
    sprintstatus.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sprintstatus, nullable=False, server_default='planning'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.drop_column('status')
    
    # Drop the enum type
    sa.Enum(name='sprintstatus').drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
