"""initial_migration_with_notes_and_notifications

Revision ID: a0830ec35eb7
Revises: 
Create Date: 2025-11-24 17:58:39.089581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0830ec35eb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Sprint table removal and task.sprint_id removed - handled manually
    with op.batch_alter_table('task', schema=None) as batch_op:
        # Check and drop foreign key constraint if exists
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        fkeys = inspector.get_foreign_keys('task')
        for fk in fkeys:
            if fk['constrained_columns'] == ['sprint_id']:
                batch_op.drop_constraint(fk['name'], type_='foreignkey')
        
        # Check and drop column if exists
        columns = [col['name'] for col in inspector.get_columns('task')]
        if 'sprint_id' in columns:
            batch_op.drop_column('sprint_id')
    
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('parent_note_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'login_info', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'note', ['parent_note_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('related_task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('action_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'task', ['related_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('task_sprint_id_fkey'), 'sprint', ['sprint_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_read')
        batch_op.drop_column('action_url')
        batch_op.drop_column('related_task_id')
        batch_op.drop_column('notification_type')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_resolved')
        batch_op.drop_column('parent_note_id')
        batch_op.drop_column('created_by')

    op.create_table('sprint',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('goal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sprint_pkey'))
    )
    # ### end Alembic commands ###
