"""Added is_deleted, deadline, team description, and default status

Revision ID: e9c486202457
Revises: 78ca9f699929
Create Date: 2025-07-13 14:44:40.667877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c486202457'
down_revision = '78ca9f699929'
branch_labels = None
depends_on = None


def upgrade():
    # 🔧 Step 1: Update existing nulls in project and team
    op.execute("UPDATE project SET is_deleted = false WHERE is_deleted IS NULL;")
    op.execute("UPDATE team SET is_deleted = false WHERE is_deleted IS NULL;")

    # 🔧 Step 2: Apply NOT NULL + default
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column(
            'is_deleted',
            existing_type=sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column(
            'is_deleted',
            existing_type=sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
